package eu.dissco.exportjob.domain.dwcdp;

import java.io.Serial;
import java.io.Serializable;
import lombok.Data;

@Data
public class DwCDpMaterial implements Serializable {

  @Serial
  private static final long serialVersionUID = 1L;
  private String materialEntity_pk;
  private String materialEntityID;
  private String digitalSpecimenID;
  private String collectionEvent_fk;
  private String evidenceForOccurrence_fk;
  private String derivedFromMaterialEntity_fk;
  private String derivedFromMaterialEntityID;
  private String derivationEvent_fk;
  private String isPartOfMaterialEntity_fk;
  private String isPartOfMaterialEntityID;
  private String materialRole;
  private String materialProportion;
  private String materialEntityCategory;
  private String materialEntityType;
  private String discipline;
  private String sampledFeatureType;
  private String institutionCode;
  private String institutionID;
  private String ownerInstitutionCode;
  private String ownerInstitutionID;
  private String collectionCode;
  private String collectionID;
  private String catalogNumber;
  private String otherCatalogNumbers;
  private String collectorNumber;
  private String collectedBy;
  private String collectedBy_fk;
  private String collectedByID;
  private String objectQuantity;
  private String objectQuantityType;
  private String preparations;
  private String disposition;
  private String measuredMassInGrams;
  private String verbatimMass;
  private String verbatimLabel;
  private String associatedSequences;
  private String materialReferences;
  private String treatments;
  private String handlingRequirements;
  private String hazardType;
  private String hazardRemarks;
  private String damageRemarks;
  private String materialDescription;
  private String materialEntityRemarks;
  private String verbatimIdentification;
  private String typeStatus;
  private String typeDesignationType;
  private String typeOfType;
  private String typifiedName;
  private String identifiedBy;
  private String identifiedBy_fk;
  private String identifiedByID;
  private String dateIdentified;
  private String identificationReferences;
  private String identificationVerificationStatus;
  private String identificationRemarks;
  private String taxonID;
  private String scientificNameID;
  private String scientificName;
  private String scientificNameAuthorship;
  private String vernacularName;
  private String taxonRank;
  private String classificationSystem;
  private String modified;
  private String provenance_fk;
  private String usagePolicy_fk;
  private String owner;
  private String owner_fk;
  private String license;
  private String informationWithheld;
  private String dataGeneralizations;
  private String feedbackURL;
}
