package eu.dissco.exportjob.domain.dwcdp;

import java.io.Serial;
import java.io.Serializable;
import lombok.Data;

@Data
public class DwcDpMedia implements Serializable {
  
  @Serial
  private static final long serialVersionUID = 1L;
  private String mediaID;
  private String derivedFromMediaID;
  private String isPartOfMediaID;
  private String mediaType;
  private String title;
  private String description;
  private String caption;
  private String subtypeLiteral;
  private String subtypeIRI;
  private String collectionCode;
  private String collectionID;
  private String CreateDate;
  private String timeOfDay;
  private String digitizationDate;
  private String captureDevice;
  private Double frameRate;
  private String resourceCreationTechnique;
  private Double sample_rate;
  private String modified;
  private String language;
  private String languageIRI;
  private String MetadataDate;
  private String metadataLanguageLiteral;
  private String metadataLanguageIRI;
  private String providerManagedID;
  private String available;
  private String hasServiceAccessPoint;
  private String serviceExpectation;
  private String accessURI;
  private String format;
  private String formatIRI;
  private String variantLiteral;
  private String variantIRI;
  private String variantDescription;
  private Integer PixelXDimension;
  private Integer PixelYDimension;
  private String hashFunction;
  private String hashValue;
  private String furtherInformationURL;
  private String commenterLiteral;
  private String commenterID;
  private String comments;
  private String Rating;
  private String reviewerLiteral;
  private String reviewerID;
  private String reviewerComments;
  private String physicalSetting;
  private String subjectCategory;
  private String subjectCategoryIRI;
  private String subjectCategorySource;
  private String tag;
  private String subjectPartLiteral;
  private String subjectPartIRI;
  private String subjectOrientationLiteral;
  private String subjectOrientationIRI;
  private Double startTime;
  private Double endTime;
  private String startTimestamp;
  private String endTimestamp;
  private Double mediaDuration;
  private Double mediaSpeed;
  private Double freqHigh;
  private Double freqLow;
  private Double xFrac;
  private Double yFrac;
  private Double heightFrac;
  private Double widthFrac;
  private Integer radius;
}
